export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_ERROR = "LOGIN_ERROR";
export const LOGIN_IN_PROGRESS ="LOGIN_IN_PROGRESS";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_ERROR = "LOGOUT_ERROR";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SET_CURRENT_USER= "SET_CURRENT_USER";
export const SIGNUP_ERROR = "SIGNUP_ERROR";


export const FETCH_FEEDBACK_ERROR ="FETCH_FEEDBACK_ERROR";
export const FETCH_FEEDBACK_SUCCESS ="FETCH_FEEDBACK_SUCCESS";
export const FETCH_FEEDBACK_INPROGRESS ="FETCH_FEEDBACK_INPROGRESS";


export const DELETE_FEEDBACK_ERROR ="DELETE_FEEDBACK_ERROR";
export const DELETE_FEEDBACK_SUCCESS ="DELETE_FEEDBACK_SUCCESS";
export const DELETE_FEEDBACK_INPROGRESS ="DELETE_FEEDBACK_INPROGRESS";
